"""empty message

Revision ID: 01358a8a15eb
Revises: baa22795ec00
Create Date: 2025-07-05 11:17:19.780405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01358a8a15eb'
down_revision: Union[str, Sequence[str], None] = 'baa22795ec00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('s3_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'videos', ['s3_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    op.drop_column('videos', 's3_key')
    # ### end Alembic commands ###
