"""Postgres public schema

Revision ID: 0cc360d993be
Revises: 
Create Date: 2025-06-26 20:29:01.739864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc360d993be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_games_id'), 'games', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_games_title'), 'games', ['title'], unique=False, schema='public')
    op.create_table('lingoplay_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='public'
    )
    op.create_index(op.f('ix_public_lingoplay_user_email'), 'lingoplay_user', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_lingoplay_user_id'), 'lingoplay_user', ['id'], unique=False, schema='public')
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.lingoplay_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_tokens_id'), 'user_tokens', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True, schema='public')
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.lingoplay_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_videos_id'), 'videos', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_videos_title'), 'videos', ['title'], unique=False, schema='public')
    op.create_table('videos_games_association',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['public.games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['public.videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'game_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos_games_association', schema='public')
    op.drop_index(op.f('ix_public_videos_title'), table_name='videos', schema='public')
    op.drop_index(op.f('ix_public_videos_id'), table_name='videos', schema='public')
    op.drop_table('videos', schema='public')
    op.drop_index(op.f('ix_public_user_tokens_refresh_token'), table_name='user_tokens', schema='public')
    op.drop_index(op.f('ix_public_user_tokens_id'), table_name='user_tokens', schema='public')
    op.drop_table('user_tokens', schema='public')
    op.drop_index(op.f('ix_public_lingoplay_user_id'), table_name='lingoplay_user', schema='public')
    op.drop_index(op.f('ix_public_lingoplay_user_email'), table_name='lingoplay_user', schema='public')
    op.drop_table('lingoplay_user', schema='public')
    op.drop_index(op.f('ix_public_games_title'), table_name='games', schema='public')
    op.drop_index(op.f('ix_public_games_id'), table_name='games', schema='public')
    op.drop_table('games', schema='public')
    # ### end Alembic commands ###
