"""empty message

Revision ID: 2276a549a33c
Revises: 4158c57ba78f
Create Date: 2025-06-29 17:14:00.286591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2276a549a33c'
down_revision: Union[str, Sequence[str], None] = '4158c57ba78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos_games_association')
    op.add_column('videos', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'videos', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'game_id')
    op.create_table('videos_games_association',
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('videos_games_association_game_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('videos_games_association_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'game_id', name=op.f('videos_games_association_pkey'))
    )
    # ### end Alembic commands ###
