"""empty message

Revision ID: 4158c57ba78f
Revises: 6cc550c33e2d
Create Date: 2025-06-29 17:03:32.373698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4158c57ba78f'
down_revision: Union[str, Sequence[str], None] = '6cc550c33e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_games_id'), table_name='games')
    op.drop_index(op.f('ix_public_games_title'), table_name='games')
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.drop_index(op.f('ix_public_lingoplay_user_email'), table_name='lingoplay_user')
    op.drop_index(op.f('ix_public_lingoplay_user_id'), table_name='lingoplay_user')
    op.create_index(op.f('ix_lingoplay_user_email'), 'lingoplay_user', ['email'], unique=True)
    op.create_index(op.f('ix_lingoplay_user_id'), 'lingoplay_user', ['id'], unique=False)
    op.drop_index(op.f('ix_public_user_tokens_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_public_user_tokens_refresh_token'), table_name='user_tokens')
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True)
    op.drop_index(op.f('ix_public_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_public_videos_title'), table_name='videos')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_index(op.f('ix_public_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_public_videos_id'), 'videos', ['id'], unique=False)
    op.drop_index(op.f('ix_user_tokens_refresh_token'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.create_index(op.f('ix_public_user_tokens_refresh_token'), 'user_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_public_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_lingoplay_user_id'), table_name='lingoplay_user')
    op.drop_index(op.f('ix_lingoplay_user_email'), table_name='lingoplay_user')
    op.create_index(op.f('ix_public_lingoplay_user_id'), 'lingoplay_user', ['id'], unique=False)
    op.create_index(op.f('ix_public_lingoplay_user_email'), 'lingoplay_user', ['email'], unique=True)
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.create_index(op.f('ix_public_games_title'), 'games', ['title'], unique=False)
    op.create_index(op.f('ix_public_games_id'), 'games', ['id'], unique=False)
    # ### end Alembic commands ###
