"""Videos path is unique

Revision ID: 6cc550c33e2d
Revises: 0cc360d993be
Create Date: 2025-06-27 11:04:37.012334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc550c33e2d'
down_revision: Union[str, Sequence[str], None] = '0cc360d993be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_tokens_user_id_fkey'), 'user_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'user_tokens', 'lingoplay_user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'videos', ['path'], schema='public')
    op.drop_constraint(op.f('videos_user_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'lingoplay_user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('videos_games_association_video_id_fkey'), 'videos_games_association', type_='foreignkey')
    op.drop_constraint(op.f('videos_games_association_game_id_fkey'), 'videos_games_association', type_='foreignkey')
    op.create_foreign_key(None, 'videos_games_association', 'games', ['game_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'videos_games_association', 'videos', ['video_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos_games_association', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'videos_games_association', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('videos_games_association_game_id_fkey'), 'videos_games_association', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('videos_games_association_video_id_fkey'), 'videos_games_association', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'videos', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('videos_user_id_fkey'), 'videos', 'lingoplay_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'videos', schema='public', type_='unique')
    op.drop_constraint(None, 'user_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_tokens_user_id_fkey'), 'user_tokens', 'lingoplay_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
