"""empty message

Revision ID: baa22795ec00
Revises: dada244bc5e4
Create Date: 2025-07-04 20:10:51.143639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa22795ec00'
down_revision: Union[str, Sequence[str], None] = 'dada244bc5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumblnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumblnail_path')
    # ### end Alembic commands ###
