"""empty message

Revision ID: bae6673a843a
Revises: 2276a549a33c
Create Date: 2025-06-30 16:07:32.371910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae6673a843a'
down_revision: Union[str, Sequence[str], None] = '2276a549a33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lingoplay_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_lingoplay_users_email'), 'lingoplay_users', ['email'], unique=True)
    op.drop_index(op.f('ix_lingoplay_user_email'), table_name='lingoplay_user', if_exists=True)
    op.drop_index(op.f('ix_lingoplay_user_id'), table_name='lingoplay_user', if_exists=True)
    op.execute("DROP TABLE IF EXISTS lingoplay_user CASCADE")
    op.drop_index(op.f('ix_games_id'), table_name='games', if_exists=True)
    op.drop_constraint(op.f('user_tokens_user_id_fkey'), 'user_tokens', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'user_tokens', 'lingoplay_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('videos', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_videos_id'), table_name='videos', if_exists=True)
    op.drop_constraint(op.f('videos_user_id_fkey'), 'videos', type_='foreignkey', if_exists=True)
    op.drop_constraint(op.f('videos_game_id_fkey'), 'videos', type_='foreignkey', if_exists=True)
    op.create_foreign_key(None, 'videos', 'lingoplay_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'videos', 'games', ['game_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_game_id_fkey'), 'videos', 'games', ['game_id'], ['id'])
    op.create_foreign_key(op.f('videos_user_id_fkey'), 'videos', 'lingoplay_user', ['user_id'], ['id'])
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.alter_column('videos', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('user_tokens_user_id_fkey'), 'user_tokens', 'lingoplay_user', ['user_id'], ['id'])
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('lingoplay_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('lingoplay_user_pkey')),
    sa.UniqueConstraint('username', name=op.f('lingoplay_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lingoplay_user_id'), 'lingoplay_user', ['id'], unique=False)
    op.create_index(op.f('ix_lingoplay_user_email'), 'lingoplay_user', ['email'], unique=True)
    op.drop_index(op.f('ix_lingoplay_users_email'), table_name='lingoplay_users')
    op.drop_table('lingoplay_users')
    # ### end Alembic commands ###
